// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdn_TVoYfgWm1OBnWMC4hdG9rvyyA4egk',
    appId: '1:274076043916:web:22a42282694a30c7df49a9',
    messagingSenderId: '274076043916',
    projectId: 'sjm-instargram',
    authDomain: 'sjm-instargram.firebaseapp.com',
    storageBucket: 'sjm-instargram.appspot.com',
    measurementId: 'G-0NBWXMR9EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9llzk745qu0rGFfvbeu1ic97OrloZYc8',
    appId: '1:274076043916:android:be8c53d22ee27939df49a9',
    messagingSenderId: '274076043916',
    projectId: 'sjm-instargram',
    storageBucket: 'sjm-instargram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvIjb9NIrhne6cIY1JNnfOjfWYI6GjjIM',
    appId: '1:274076043916:ios:4c97087a040b317bdf49a9',
    messagingSenderId: '274076043916',
    projectId: 'sjm-instargram',
    storageBucket: 'sjm-instargram.appspot.com',
    iosClientId: '274076043916-4g3ok8fdrggr6hovelj27v6h75atrlm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
